### ISSUE TITLE
iOS setting error 'DaumMap/MTMapView.h' file not found

### ISSUE THREAD

**Issue by zeddjeong** [asata/react-native-daummap#1]
안녕하세요. 다음맵 패키지를 iOS 에 세팅하던 중 에러가 발생했는데

혼자 해결이 안되서 글 올립니다.

* 에러 내용
node_modules/react-native-daummap/ios/DaumMap/DaumMap.m:3:9: fatal error: 'DaumMap/MTMapView.h' file not found
#import <DaumMap/MTMapView.h>

* iOS 프로젝트 세팅
Framework Search paths : $(PROJECT_DIR)/DaumMap.embeddedframework (non-recursive)
Header Search paths : $(SRCROOT)/../node_modules/react-native-daummap/ios/DaumMap

<img width="626" alt="2018-08-07 6 02 46" src="https://user-images.githubusercontent.com/30224606/43766050-6fe38ae0-9a6c-11e8-8113-9dac89880586.png">

<img width="274" alt="2018-08-07 6 03 03" src="https://user-images.githubusercontent.com/30224606/43766069-7a24f534-9a6c-11e8-94b0-ad070c2e3f5b.png">

<img width="258" alt="2018-08-07 6 06 51" src="https://user-images.githubusercontent.com/30224606/43766154-b2066cd0-9a6c-11e8-8b0e-9d189ad4d5a0.png">

**Comment by noproblemo** [comment]
저도 동일 증상으로 이슈를 막 등록시키려 했습니다!

**Comment by noproblemo** [comment]
저도 아래와 같이 @zeddjeong 님과 같이 헤더파일을 찾지못하는 문제여서 잔머리를 굴렸습니다. 

![image](https://user-images.githubusercontent.com/4454645/43850827-fca93c06-9b73-11e8-846f-0bd43978e9be.png)

그래서, 아래 그림과 같이 에러 리스트에서 DaumMap을 선택하고 target에서 DaumMap을 선택하여 Build Setting의 **Framework Search Path** 의 값을 ``$(PROJECT_DIR)/../../../ios/**`` 에서 ``$(PROJECT_DIR)`` 로 수정 후 

![image](https://user-images.githubusercontent.com/4454645/43851113-bd470a42-9b74-11e8-992d-63dc2b815752.png)

Daum SDK의 ``DaumMap.framework``을 ``node_modules/react-native-daummap/ios/`` 로 카피하였습니다. 

![image](https://user-images.githubusercontent.com/4454645/43851220-01def584-9b75-11e8-9624-10b95d93cd34.png)

이제 다시 실행해보시면 에러없이 지도를 보실 수 있을 겁니다. 
꼼수로 해결했네요.

**Comment by zeddjeong** [comment]
안녕하세요 @noproblemo 님
님이 올리신대로 세팅하니 이번에는 새로운 에러가 나오네요 ㅜ.ㅜ

아예 프로젝트를 새로 하나 만들고 클린한 상태로  daummap을 붙여봤는데

이번에는 libDaumMap.a 파일에서 에러가 터지네요

분명히 Link Binary With Libraries 에 libDaumMap.a 파일이 적용되었는데 말이죠,,,

짐작가는 부분이 있으시다면 답글 부탁드립니다.

--에러내용--
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MTMapPOIItem", referenced from:
      objc-class-ref in libDaumMap.a(DaumMap.o)
  "_OBJC_CLASS_$_MTMapPoint", referenced from:
      objc-class-ref in libDaumMap.a(DaumMap.o)
  "_OBJC_CLASS_$_MTMapView", referenced from:
      objc-class-ref in libDaumMap.a(DaumMap.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

--환경설정--
<img width="517" alt="2018-08-10 12 06 22" src="https://user-images.githubusercontent.com/30224606/43937045-75162f28-9c96-11e8-9484-7c7d21d24d4e.png">
<img width="721" alt="2018-08-10 12 06 29" src="https://user-images.githubusercontent.com/30224606/43937046-754aa640-9c96-11e8-8f6c-1969b6b3bfa5.png">
<img width="1249" alt="2018-08-10 12 06 48" src="https://user-images.githubusercontent.com/30224606/43937047-75830fd0-9c96-11e8-8c0c-c01c84277b13.png">
<img width="620" alt="2018-08-10 12 07 38" src="https://user-images.githubusercontent.com/30224606/43937048-75c70c30-9c96-11e8-8330-d03bb8a6919d.png">

**Comment by noproblemo** [comment]
아무래도 

![framework](https://user-images.githubusercontent.com/899614/40571726-12ff54e8-60d9-11e8-974d-34767ddb460e.gif)

를 생략하신것 같은데요?

**Comment by zeddjeong** [comment]
@noproblemo 님 말대로 하니까 해결됐네요 ㅎㅎ

정말 감사합니다~!!!

**Comment by noproblemo** [comment]
@zeddjeong 잘 되었다니 다행이네요. :)
