### ISSUE TITLE
질문입니다.

### ISSUE THREAD

**Issue by thezoneapp** [asata/react-native-daummap#14]
저는 windows 10, Visual Studio Code를 이용하고 있습니다.
sample 소스대로 따라했는데 안돼서 며칠째 삽질하고 있습니다 ㅠ.ㅠ

Android
1. In your android/settings.gradle file, make the following additions:
   --> 위치가 project/node_modules/react-native-daummap 하위 폴더에 위치하는게 맞나요?
2. In your android/app/build.gradle file, add the :react-native-splash-screen project as a compile-time dependency:
   --> 위치가 project/node_modules/react-native-daummap 하위 폴더에 위치하는게 맞나요?
3. Update the MainApplication.java file to use react-native-splash-screen via the following changes:
   --> 위치가 project/node_modules/react-native-daummap 하위 폴더에 위치하는게 맞나요?
         만약  MainApplication.java 파일이 없다면 만들어 주어야 하나요?

**Comment by asata** [comment]
react-native link react-native-daummap를 실행헀다면 "Manual installation"를 안 해도 됩니다.

각 파일들은 모듈이 아닌 project/android 내에 있는 파일 들입니다.
