### ISSUE TITLE
marker 사용 방법이 어떻게 되나요?

### ISSUE THREAD

**Issue by harudev** [asata/react-native-daummap#3]
문서 보고 object array형태로 MapView의 markers  prop에 전달하는거라고 추측해서

```javascript
<MapView
    initialRegion={{
    latitude: 37.5030682,
    longitude: 127.0222213,
    zoomLevel: 2,
  }}
  mapType={'Standard'}
  style={{width: 320, height: 400 }}
  markers={[
    {latitude: 37.5030682, longitude: 127.0222213, title: '테스트', draggable: true},
   ]}
        />
```
이런식으로 넣어봤는데 마커가 뜨지 않네요.
사용법이 틀린건가요?

**Comment by harudev** [comment]
@zeddjeong 님 라이브러리 잘 사용하시고 계신 것 같은데 혹시 시간괜찮으시면 답변 부탁드립니다!

**Comment by asata** [comment]
마커를 추가하는 방식은 맞습니다.
입력해 주신 코드로 동작이 되는것도 확인을 했습니다.

다만 draggable 기능이 동작하지 않는 것을 확인 했습니다.
해당 부분은 수정할 예정입니다.

**Comment by asata** [comment]
android에서는 정상 표시가 되나 
iOS에서 제대로 표시 되지 않는 문제를 확인하여 현재 수정 작업 중입니다.

@ruci06 개발 중인 OS (iOS,Android) 와 다음 지도 SDK 버전을 알려주세요.

**Comment by ruci06** [comment]
@ruci06 답이 늦어 죄송합니다. IOS 시뮬레이터로 작업중 발생했고 다음 지도 SDK는 1.3.1, react-native 버전은 0.55.4입니다.

**Comment by harudev** [comment]
@asata 답이 늦어 죄송합니다.
OS는 IOS, 다음 지도 SDK는 1.3.1, RN버전은 0.55.4 입니다.

**Comment by asata** [comment]
@ruci06 몇가지 사항을 확인을 하느라 답변이 늦어 죄송합니다.
마커 사용법은 넣은 방식으로 하는게 맞으며,
안드로이드의 경우 SDK 버전과 상관없이 정상 동작 중입니다.
다만, iOS는 1.3.0버전에서는 정상 동작을 하나 1.3.1에서는 표시가 되지 않고 있습니다.
해당하는 부분은 카카오에 문의를 한 상태입니다.

xcode 버전이 10이 아닐 경우 SDK 버전을 1.3.0으로 변경하여 사용하길 권장 합니다.
다만 10일 경우 필요한 라이브러리가 지원되지 않아 1.3.0를 사용할 수가 없습니다.

[IOS_DaumMap_SDK_1.3.0.zip](https://github.com/asata/react-native-daummap/files/2480914/IOS_DaumMap_SDK_1.3.0.zip)

**Comment by harudev** [comment]
@asata 확인 감사합니다~!
